#!/bin/bash
# -*- mode: sh; coding: utf-8-unix -*-

command_name=$(basename "$0")

function usage_exit() {
    cat << EOF >&2
Usage: $command_name file...
EOF
    exit $1
}

while getopts :h opt; do
    case $opt in
        h)
            usage_exit 0
            ;;
        \?)
            usage_exit 2
            ;;
    esac
done

args=()
for arg; do
    args+=("$(wslpath -wa "$arg")")
done
set -- "${args[@]}"

# <user> の箇所は利用者の ログインID に置き換える必要があります
/mnt/c/Users/<user>/AppData/Local/Programs/elecxzy/elecxzy.exe "$@" > /dev/null &
