#!/bin/bash
# -*- mode: sh; coding: utf-8-unix -*-

command_name=$(basename "$0")

function usage_exit() {
    cat << EOF >&2
Usage: $command_name [file]
EOF
    exit $1
}

while getopts :h opt; do
    case $opt in
        h)
            usage_exit 0
            ;;
        \?)
            usage_exit 2
            ;;
    esac
done

shift $((OPTIND - 1))

if [ $# -gt 1 ]; then
    usage_exit 2
fi

function message() {
    echo "$command_name: $1" >&2
    exit 1
}

args=()
for arg; do
    if [ ! -f "$arg" ]; then
       message "存在するファイルを指定してください"
    fi
    args+=("$(wslpath -wa -- "$arg")")
done
set -- "${args[@]}"

# <user> の箇所は利用者の ログインID に置き換えてください
/mnt/c/Users/<user>/AppData/Local/Programs/elecxzy/elecxzy.exe "$@" > /dev/null &
