#+STARTUP: showall indent

* Windows Subsystem for Linux Utilities

Windows Subsystem for Linux で動作するユティリティコマンド群です。

各コマンドでは wslcommon をインポートしていますので、コマンドと同じ場所（コマンドパスが通ったディレクトリ）に
格納してご利用ください。

** wslstart

cygstart 的コマンドです。

詳しくは以下を参照してください。

- [[https://www49.atwiki.jp/ntemacs/pages/62.html][WSL で cygstart 的コマンドを使うための設定]]

また、スクリプトの初めにあるコメントも参照ください。

** sglstart

singleton な動きをする cygstart 的コマンドです。

詳しくは以下を参照してください。

- [[https://www49.atwiki.jp/ntemacs/pages/63.html][singleton な動きをする cygstart 的コマンドを使うための設定 （WSL版）]]

また、スクリプトの初めにあるコメントも参照ください。

** wslln

ln 的コマンドです。

Windows 10 Fall Creators Update の Windows Subsystem for Linux では、DrvFS ファイルシステム上
にある NTFS シンボリックリンクを表示できるようになりました。ただし、ln コマンドで
NTFS シンボリックリンクを作成することはできません。
本コマンドは、DrvFs ファイルシステム上にシンボリックリンクを作成する場合は NTFS シンボリックリンク
を、DrvFs ファイルシステム以外にシンボリックリンクを作成する場合は WSL 本来のシンボリックリンク
を作成するように動作する ln と mklink の機能をラッパーしたコマンドです。ln の alias として
使うのも良いと思います。

なお、コマンド実行時に -s オプションを指定しない場合は、ハードリンクを作成します。
ハードリンクは、ファイルシステムによる違いはないようですので、統一して ln コマンドを利用する
ようにしています。

*** wslln -s target link 実行時のシンボリックリンク作成ルール

|----------------+----------------+----------------------------|
| target の場所  | link の場所    | 代替コマンドの実行方法     |
|----------------+----------------+----------------------------|
| DrvFs 配下     | DrvFs 配下     | mklink を実行 [1]          |
| DrvFs 配下以外 | DrvFs 配下     | 許可しない（エラーとする） |
| DrvFs 配下     | DrvFs 配下以外 | ln -s を実行               |
| DrvFs 配下以外 | DrvFs 配下以外 | ln -s を実行               |
|----------------+----------------+----------------------------|

[1] ターゲットファイルの指定が絶対パスの場合は、パスの途中にあるシンボリックリンクを取り除きます。
相対パスの場合は、パスをそのまま利用します。

*** -a オプション

-a オプション（absolute オプション）を付けると、ターゲットファイルのパスを絶対パスに変換してから
リンクを作成します。ln コマンドには無いオプションとなります。

*** 今後の計画

emacs からシンボリックリンクを作成する際に（make-symbolic-link 中で）このコマンドを使用するように
対応する予定です。
