#!/bin/bash
# -*- mode: sh; coding: utf-8-unix -*-

function usage_exit() {
    local command_name=$(basename "$0")
    cat << EOF >&2
Usage: $command_name file
       $command_name -c
       $command_name -h
EOF
    exit 1
}

function clean_all() {
    wslstart -c
    exit $?
}

while getopts :ch opt; do
    case $opt in
        c)
            clean_all
            ;;
        h)
            usage_exit
            ;;
        \?)
            usage_exit
            ;;
    esac
done

shift $(($OPTIND - 1))

if [ $# -ne 1 ]; then
    usage_exit
fi

if [ -f "$1" ]; then

    file_name=$(basename "$1")

    # ウィンドウのタイトルにファイル名の文字列を含むものがあればポップアップする
    if winactivate.exe "$file_name" 2> /dev/null; then
        exit 0
    fi
fi

wslstart -- "$1"
