#!/bin/bash
# -*- mode: sh; coding: utf-8-unix -*-

command_name=$(basename "$0")

function usage_exit() {
    cat << EOF >&2
Usage: $command_name target
       $command_name -h
EOF
    exit $1
}

while getopts :h opt; do
    case $opt in
        h)
            usage_exit 0
            ;;
        \?)
            usage_exit 2
            ;;
    esac
done

shift $((OPTIND - 1))

if [ $# -ne 1 ]; then
    usage_exit 2
fi

function winactivate() {
    # ウィンドウのタイトルに引数の文字列を含むものがあればアクティベートする
    (cd; winactivate.exe "$1" 2> /dev/null)
}

# ターゲットが存在するか？
if [ -e "$1" ]; then
    target_path=$(readlink -m -- "$1")
    base_name=$(basename -- "$target_path")

    winactivate "$base_name"
    if [ $? -eq 0 ]; then
        exit 0
    fi

    wslstart -- "$1"

    # フォルダを新たに開いた場合、ウィンドウにフォーカスが写らない場合があるのでアクティベートする
    if [ -d "$target_path" ]; then
        sleep 0.5
        winactivate "$base_name"
    fi
else
    wslstart -- "$1"
fi
