#!/bin/bash
# -*- mode: sh; coding: utf-8-unix -*-

function usage_exit() {
    local command_name
    command_name=$(basename "$0")

    cat << EOF >&2
Usage: $command_name command
       $command_name -h
EOF
    exit $1
}

while getopts :h opt; do
    case $opt in
        h)
            usage_exit 0
            ;;
        \?)
            usage_exit 2
            ;;
    esac
done

shift $((OPTIND - 1))

if [ $# -eq 0 ]; then
    usage_exit 2
fi

process_id=$(mktemp -t "$command_name.XXXXXXXXXX")
shell_command=$(mktemp -t "$command_name.XXXXXXXXXX")

trap 'rm -f "$process_id" "$shell_command"' 0

quote_pwd=$(printf '%q' "$PWD")
quote_cmd=''

for arg in "$@"; do
    quote_arg=$(printf '%q' "$arg")
    quote_cmd+=" $quote_arg"
done

# 本コマンドで exe コマンドを実行すると、"tcgetpgrp failed: Not a tty"という
# メッセージが表示されます。このメッセージを表示しないようにするために cat の
# フィルターを通すようにしています。メッセージが消える理由は分わかりません。
if [[ "$1" =~ \.exe$ ]]; then
    quote_cmd+=' | cat'
fi

cat << EOF > "$shell_command"
echo \$$ > '$process_id'
exec < /proc/$$/fd/0 > /proc/$$/fd/1 2> /proc/$$/fd/2
LANG=$LANG
cd $quote_pwd
$quote_cmd
EOF

trap 'trap "" 1 2 3 15; "$0" kill -- -$(cat "$process_id")' 1 2 3 15

powershell.exe -Command Start-Process bash.exe "'$shell_command'" -WindowStyle Hidden -Wait -Verb runas &
wait $!
