#!/bin/bash
# -*- mode: sh; coding: utf-8-unix -*-

source wslcommon
command_name=$(basename "$0")

function usage_exit() {
    cat << EOF >&2
Usage: $command_name [-s] [-f] [-a] target link
       $command_name [-s] [-f] [-a] target
       $command_name -h
EOF
    exit $1
}

symlink_flg=0
force_flg=0
absolute_flg=0

while getopts :sfah opt; do
    case $opt in
        s)
            symlink_flg=1
            ;;
        f)
            force_flg=1
            ;;
        a)
            absolute_flg=1
            ;;
        h)
            usage_exit 0
            ;;
        \?)
            usage_exit 2
            ;;
    esac
done

shift $((OPTIND - 1))

if [ $# -ne 1 ] && [ $# -ne 2 ]; then
    usage_exit 2
fi

function message() {
    echo "$command_name: $1" >&2
    exit 1
}

if [ $# -eq 1 ]; then
    set -- "$1" .
fi

target_basename=$(basename -- "$1")

if [ "$target_basename" = "." ] || [ "$target_basename" = ".." ]; then
    target_wsl_path=$(readlink -m -- "$1")
    target_basename=$(basename -- "$target_wsl_path")
else
    target_dirname=$(dirname -- "$1")
    target_wsl_path=$(readlink -m -- "$target_dirname")
    target_wsl_path+=/$target_basename
fi

link_dirname=$(dirname -- "$2")
link_basename=$(basename -- "$2")
link_wsl_path=$(readlink -m -- "$link_dirname")
link_wsl_path+=/$link_basename

if [ -d "$link_wsl_path" ]; then
    link_wsl_dir=$link_wsl_path
else
    link_wsl_dir=$(dirname -- "$link_wsl_path")
fi

# DrvFs ファイルシステム上にシンボリックリンクを作成しようとしているか？
if [ $symlink_flg -eq 1 ] && drvfs_p "$link_wsl_dir"; then

    # ターゲットファイルが DrvFs ファイルシステム上にあるか？
    if drvfs_p "$target_wsl_path"; then

        # -a オプションが指定されたか、ターゲットファイルが絶対パスでないか、
        # 絶対パスの場合は DrvFs ファイルシステムを示すパスとなっているか？
        if [ $absolute_flg -eq 1 ] || [[ ! "$1" =~ ^/ ]] || drvfs_p "$1"; then

            if [ $absolute_flg -eq 1 ]; then
                target_win_path=$(winpath "$target_wsl_path")
            else
                target_win_path=$(winpath "$1")
            fi

            if [ -d "$link_wsl_path" ]; then
                link_win_path=$(winpath "$link_wsl_path")
                link_win_path+='\'$target_basename
            else
                link_win_path=$(winpath "$link_wsl_dir")
                link_win_path+='\'$link_basename
            fi

            option=''

            if [ -d "$target_wsl_path" ]; then
                option='/d'
            fi

            if [ $force_flg -eq 1 ]; then
                rm -f "$link_wsl_path" 2> /dev/null
            fi

            cmd mklink $option "$link_win_path" "$target_win_path" 2>&1 > /dev/null | sed "s/^/$command_name: /" >&2
            exit ${PIPESTATUS[0]}
        else
            message '-a オプションを付けることにより、リンクを作成することができます'
        fi
    else
        message 'このファイルのリンクを DrvFs 配下に作成することはできません'
    fi
else
    option=''

    if [ $symlink_flg -eq 1 ]; then
        option='-s'
    fi

    if [ $force_flg -eq 1 ]; then
        option+=' -f'
    fi

    if [ $absolute_flg -eq 1 ]; then
        set -- "$target_wsl_path" "$2"
    fi

    ln $option -- "$@" 2>&1 | sed "s/^ln:/$command_name:/" >&2
    exit ${PIPESTATUS[0]}
fi
