#!/bin/bash
# -*- mode: sh; coding: utf-8-unix -*-

source wslcommon
command_name=$(basename "$0")

function usage_exit() {
    cat << EOF >&2
Usage: $command_name [-u|-w|-m] path
       $command_name -h
EOF
    exit $1
}

win_path_flg=0
wsl_path_flg=0
mix_path_flg=0

while getopts :awumh opt; do
    case $opt in
        w)
            win_path_flg=1
            ;;
        u)
            wsl_path_flg=1
            ;;
        m)
            mix_path_flg=1
            ;;
        h)
            usage_exit 0
            ;;
        \?)
            usage_exit 2
            ;;
    esac
done

case $((win_path_flg + wsl_path_flg + mix_path_flg)) in
    0)
        wsl_path_flg=1
        ;;
    1)
        ;;
    *)
        usage_exit 2
        ;;
esac

shift $(($OPTIND - 1))

if [ $# -ne 1 ]; then
    usage_exit 2
fi

function message() {
    echo "$command_name: $1" >&2
    exit 1
}

if [ $win_path_flg -eq 1 ]; then
    wsl_path=$(readlink -m -- "$1")
    if check_drvfs_wslpath "$wsl_path"; then
        winpath "$wsl_path"
    else
        message "変換できませんでした"
    fi

elif [ $mix_path_flg -eq 1 ]; then
    wsl_path=$(readlink -m -- "$1")
    if check_drvfs_wslpath "$wsl_path"; then
        winpath "$wsl_path" | sed 's!\\!/!g'
    else
        message "変換できませんでした"
    fi

elif [ $wsl_path_flg -eq 1 ]; then
    win_path=$(echo "$1" | sed 's!/!\\!g')
    if check_drvfs_winpath "$win_path"; then
        wslpath "$win_path"
    else
        message "変換できませんでした"
    fi
fi
