#!/bin/bash
# -*- mode: sh; coding: utf-8-unix -*-

source wslcommon
command_name=$(basename "$0")

function usage_exit() {
    cat << EOF >&2
Usage: $command_name [-u|-w|-m] [-a] path
       $command_name -h
EOF
    exit $1
}

win_path_flg=0
wsl_path_flg=0
mix_path_flg=0
absolute_flg=0

while getopts :awumh opt; do
    case $opt in
        w)
            win_path_flg=1
            ;;
        u)
            wsl_path_flg=1
            ;;
        m)
            mix_path_flg=1
            ;;
        a)
            absolute_flg=1
            ;;
        h)
            usage_exit 0
            ;;
        \?)
            usage_exit 2
            ;;
    esac
done

case $((win_path_flg + wsl_path_flg + mix_path_flg)) in
    0)
        wsl_path_flg=1
        ;;
    1)
        ;;
    *)
        usage_exit 2
        ;;
esac

shift $((OPTIND - 1))

if [ $# -ne 1 ]; then
    usage_exit 2
fi

function message() {
    echo "$command_name: $1" >&2
    exit 1
}

if [ $wsl_path_flg -eq 1 ]; then
    win_path=$(echo "$1" | sed 's!/!\\!g')
    wsl_path=$(wslpath "$win_path")

    if [ $? -eq 0 ]; then
        if [ $absolute_flg -eq 1 ]; then
            wsl_path=$(readlink -m -- "$wsl_path")
        fi
        echo "$wsl_path"
    else
        message "変換できませんでした"
    fi
else
    if [ $absolute_flg -eq 1 ]; then
        wsl_path=$(readlink -m -- "$1")
    else
        wsl_path=$1
    fi
    win_path=$(winpath "$wsl_path")

    if [ $? -eq 0 ]; then
        if [ $mix_path_flg -eq 1 ]; then
            win_path=$(echo "$win_path" | sed 's!\\!/!g')
        fi
        echo "$win_path"
    else
        message "変換できませんでした"
    fi
fi
