#!/bin/bash
# -*- mode: sh; coding: utf-8-unix -*-

source wslcommon
command_name=$(basename "$0")

function usage_exit() {
    cat << EOF >&2
Usage: $command_name target
       $command_name -h
EOF
    exit $1
}

while getopts :h opt; do
    case $opt in
        h)
            usage_exit 0
            ;;
        \?)
            usage_exit 2
            ;;
    esac
done

shift $((OPTIND - 1))

if [ $# -ne 1 ]; then
    usage_exit 2
fi

function message() {
    echo "$command_name: $1" >&2
    exit 1
}

# ターゲットファイルが存在するか？
if [ -e "$1" ]; then
    wsl_path=$(readlink -m -- "$1")
    win_path=$(winpath "$wsl_path")

    # WSL path を Windows path に変換できたか？
    if [ $? -eq 0 ]; then
        start "$win_path"
    else
        message '指定したファイルは開くことができません'
    fi
else
    # ターゲットファイルが存在しない場合（コマンドや URL が指定された場合）は、そのまま開く。
    win_path=$(echo "$1" | sed 's!/!\\!g')
    start "$win_path"
fi
