#+STARTUP: showall indent

* WSL Utilities

Windows Subsystem for Linux で動作するユティリティコマンド群です。

上位ディレクトリのコマンド群にマージ（上書き）してご利用ください。

また、DrvFs を多くマウントしている場合は、.bash_profile の .bashrc を実行している行の後に
以下の設定を追加してください。 wsl コマンドの高速化 が図られます。

#+BEGIN_EXAMPLE
source wslinit
#+END_EXAMPLE

実際には、以下のような .bash_profile を作成するのが良いと思います。mount 行を追加した場合は、
WSL のコンソールを再起動してください。

#+BEGIN_EXAMPLE
sudo sh << 'EOF'
mount -t drvfs '\\<コンピュータ名1>\<共有名>' /mnt/share1
mount -t drvfs '\\<コンピュータ名2>\<共有名>' /mnt/share2
mount -t drvfs '\\<コンピュータ名3>\<共有名>' /mnt/share3
EOF

[ -r ~/.bashrc ] && source ~/.bashrc
source wslinit
#+END_EXAMPLE

mount は /etc/fstab を設定して利用する方法もあります。Windows 10 April 2018 Update では、
wsl.conf を設定することにより自動マウントも可能となっています。
（Fall Creators Update までは、sudo mount -a が必要。）

- http://ascii.jp/elem/000/001/634/1634120/

/etc/fstab の設定で、IPアドレスを含む UNC パスに対してのマウントポイントを指定する場合、
「\\172」で始まる箇所などが８進数認識されてしまいます。この場合、２つ目の「\」を敢えて
８進数の「\134」と記載することで対策可能です。

#+BEGIN_EXAMPLE
\\134172.16.0.1\<共有名>	/mnt/share1	drvfs	defaults	0 0
#+END_EXAMPLE

認証を必要とするネットワークボリュームを利用する場合は、予め以下の設定により認証情報を
記憶させる必要があります。

- https://www.ipentec.com/document/windows-delete-stored-authentication-information

ネットワークボリュームにアクセスした際に開く認証画面で、「資格情報を記憶する」にチェック
を入れることでも登録できます。

** ■ wslpath

cygpath 的コマンドです。

常に絶対パスに対して機能する以外は、概ね cygpath コマンドと同様に動作します。

Windows 10 April 2018 Update で wslpath コマンドがサポートされましたので、いずれ不要な
コマンドになると思いますが、Update するまでの繋ぎとして利用いただければと思います。

- https://kledgeb.blogspot.jp/2018/03/wsl-142-windows-101803wsl.html

今後、本リポジトリで公開しているコマンドも Windows 10 April 2018 Update の wslpath を
使うように見直す予定です。

*** 使用方法

#+BEGIN_EXAMPLE
wslpath [-u|-w|-m] path
wslpath -h
#+END_EXAMPLE

*** コマンドオプション

**** ● -u オプション

パス名を UNIX 形式で表示します。（デフォルトの動作）

**** ● -w オプション

パス名を Windows 形式で表示します。

**** ● -m オプション

「¥」の代わりに「/」を使用する以外、-w オプションと同様に機能します。
