#+STARTUP: showall indent

* WSL Utilities ( for Windows 10 Fall Creators Update )

Windows 10 Fall Creators Update の Windows Subsystem for Linux で動作するユティリティ
コマンドです。

上位ディレクトリのコマンド群にマージ（上書き）してご利用ください。

また、DrvFs を多くマウントしている場合は、.bash_profile を以下のように設定して、wslinit
を実行してご利用ください。wsl コマンドの高速化 が図られます。

#+BEGIN_EXAMPLE
[ -r ~/.bashrc ] && source ~/.bashrc
source wslinit
#+END_EXAMPLE

UNC パスへのアクセスが必要な場合には、上位ディレクトリで紹介している /etc/fstab の設定
を以下のとおりに変更し、sudo mount -a の実行によりマウントしてからご利用ください。

#+BEGIN_EXAMPLE
\\<ホスト名称>\<共有名>	/mnt/share1	drvfs	defaults	0 0
#+END_EXAMPLE

** ■ wslpath

cygpath 的コマンドです。

常に絶対パスに対して機能する以外は、概ね cygpath コマンドと同様に動作します。

Windows 10 April 2018 Update では wslpath コマンドがサポートされましたが、Windows 10
Fall Creators Update ではサポートされていませんので、代替えのコマンドとしてご利用ください。

- https://kledgeb.blogspot.jp/2018/03/wsl-142-windows-101803wsl.html

*** 使用方法

#+BEGIN_EXAMPLE
wslpath [-u|-w|-m] [-a] path
wslpath -h
#+END_EXAMPLE

*** コマンドオプション

**** ● -u オプション

パス名を UNIX 形式で表示します。（デフォルトの動作）

**** ● -w オプション

パス名を Windows 形式で表示します。

**** ● -m オプション

「¥」の代わりに「/」を使用する以外、-w オプションと同様に機能します。

**** ● -a オプション

Windows 10 April 2018 Update でサポートされた wslpath コマンドとの互換性のために
利用可能としています。ただし、本コマンドでは、このオプションを付けても付けなくても
常に絶対パスを返す仕様としています。
